expense.debug-enabled=true
expense.range-high=1024
expense.range-low=64

quarkus.http.port=8080


expense.debug-message = Range [${expense.range-low}, ${expense.range-high}]

%dev.expense.range-low=500
%qa.expense.range-low=600